name: CI

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc

    - name: Run syntax check
      run: python -m py_compile calculator.py

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Generate documentation
      run: |
        mkdir -p docs/html
        pdoc --output-directory docs/html calculator.py

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/html/calculator/
